Add command to filter by test `@tag :tag` attributes.
randycoulman/mix_test_interactive pull request #66
Opened 2023-01-21 04:21 UTC by mikowitz

Adds the `t` command to the interactive runner.

## Usage

`t tag1 tag2`

will append `--only tag1 --only tag2` to the end of the test command being run, ensuring that only tests with `@tag :tag1` or `@tag :tag2` are run.

Like the `p` command, the list of tags can be cleared by passing `t` alone to the interactive runner.

2023-01-21 18:34 UTC, randycoulman commented
@mikowitz Thanks for the contribution! I'm quite busy for the next week or so, but I will review this as soon as I get some free time.

2023-01-21 21:04 UTC, mikowitz commented
@randycoulman sounds good! Thanks for building the bulk of this tool, and for making it so easy to add functionality.

2023-01-28 22:53 UTC, randycoulman requested changes
Thanks for your patience; sorry I didn't have time to review this sooner.

This looks great! You did a really nice job of following the conventions of the codebase, and this is a nice clean addition.

As mentioned below, this raises a question about how `p` and `t` should interact, but I think what you've done here makes sense for now.

I haven't yet pulled this branch down to test it; I'll do that once you've addressed the items below.

There are a few things missing:
- `Settings.new` needs to be updated to parse any `--only` arguments from the command line and initialize its state with those initial tag values.
- `Settings.all_tests` needs to be updated to reset the `tags` to an empty list as is done for patterns.
- `Settings.summary` needs to be updated to show the matching tags when they are set.
- `EndToEndTest` needs to be updated to test the new `t` command.

2023-01-28 22:53 UTC, randycoulman commented on lib/mix_test_interactive/settings.ex
> +    |> all_tests()
I think this is OK for now, but it raises a question about how patterns and tags should interact.

When I use the `p` command, should a subsequent `t` command clear out my patterns, or maintain them? And vice versa, should a pattern clear out any tags?

2023-01-28 22:53 UTC, randycoulman commented on lib/mix_test_interactive/settings.ex
> +
I suggest making the pattern match look more like the one for the `patterns` case. Also, `Enum.map |> List.flatten` can be simplified to `Enum.flat_map`.

#optional

```suggestion
  defp args_from_settings(%__MODULE__{tags: tags}) when length(tags) > 0 do
    tag_args = Enum.flat_map(tags, &["--only", &1])
    {:ok, tag_args}
  end
```

2024-09-17 03:59 UTC, randycoulman commented
I'm going to close this PR as stale. I am planning to work on tag filtering features in the coming weeks, and I think it'll look a little bit different than what's here. In addition, the recent changes for "config-less operation" mean there's some work to do to rebase this.

Thanks again for the contribution!

2024-09-17 03:59 UTC, closed without merging